import type { Messages } from "./types";

export const en: Messages = {
  nav: { home: "Home", live: "Live", history: "Historical", methodology: "Methodology", menu: "Open menu", close: "Close menu", language: "Language", theme: "Theme", refresh: "Auto-refresh", paused: "Paused", active: "Active", primary: "Primary navigation", light: "Light", dark: "Dark" },
  landing: { title: "Renfe is never late. Nor is it early. It arrives precisely when it means to.", titleHighlight: "Nor is it early.", body: "At Andén Infinito, we gather the public evidence from RENFE Cercanías so delays and frustration do not disappear when the journey ends.", searchLabel: "Search a line or station", searchPlaceholder: "C1, C-1, Atocha, Chamartín…", liveAction: "View today", historyAction: "View history", emptySearch: "No matching line or station.", searchError: "Search is temporarily unavailable. Try again.", summaryLive: "Live", summaryHistory: "Historical", activeTrains: "Active trains", activeDelay: "Active-journey delay", todayDelay: "Accumulated journey delay today", delayTrend: "Accumulated journey delay today", delayTrendWindow: "05:00 — 02:00 · every 30 min", footerDescription: "independent public-accountability project", methodology: "How we measure — and what we cannot claim" },
  common: {
    coverage: "Coverage", freshness: "Freshness", finalized: "Finalized", processing: "Processing", finalizationUnknown: "Finalization unknown", precision: "Precision", updated: "Updated", scheduled: "Scheduled", observed: "With evidence", punctuality: "Punctuality", mean: "Mean", median: "Median", p90: "P90", cancellation: "Canceled", missing: "Missing evidence", noData: "No data", details: "Details", direction: "Direction", directionA: "Direction A", directionB: "Direction B", line: "Line", station: "Station", loading: "Loading", state: "State", confidence: "Confidence", dataMetadata: "Data metadata", unavailable: "Unavailable", back: "Back",
    sourceHealthy: "Source healthy", sourceStale: "Source stale", sourceUnavailable: "Source unavailable", sourceOvernight: "No active service", sourceHistorical: "Historical data", sourceReference: "Reference data",
    freshnessFresh: "Fresh", freshnessStale: "Stale", freshnessUnknown: "Unknown", freshnessNotApplicable: "Not applicable",
    precisionReported: "Reported", precisionCalculated: "Calculated", precisionMixed: "Mixed", precisionAggregate: "Aggregate", precisionSchematic: "Schematic inference",
    confidenceHigh: "High", confidenceMedium: "Medium", confidenceLow: "Low", confidenceUnavailable: "Unavailable",
    evidenceReportedOnly: "Reported only", evidenceObservedPresence: "Observed presence", evidenceSkipped: "Skipped", evidenceCanceled: "Canceled", evidenceMissing: "Missing evidence", evidencePending: "Pending",
    algorithmNone: "Algorithm version unavailable", algorithmMixed: "Mixed algorithm versions",
  },
  live: { title: "Today’s service", networkTitle: "All lines", comparison: "Usual comparison", comparisonUnavailable: "This comparison is not available from the current public data contract.", comparisonInsufficient: "There is not enough comparable evidence yet.", trains: "Active trains", activeTrains: "active trains", schematic: "Schematic", dailyMatrix: "Daily matrix", viewMode: "Line view", towards: "Towards", inferred: "Position inferred from available evidence; this is not GPS.", reported: "Position reported at a stop", positionUnavailable: "Exact position unavailable", lastPositionUpdate: "Last position update", expectedTime: "Scheduled time", delay: "Delay", nextArrival: "Scheduled arrival", probableArrival: "Probable arrival", actualArrival: "Actual arrival", nextStop: "Next stop", previousStop: "Previous stop", stoppedAt: "Stopped at", sourceArrival: "Reported arrival", observedPresence: "Observed presence", autoRefresh: "Refreshes every 30s", refreshing: "Refreshing data", hiddenTabPause: "Refresh pauses in hidden tabs", overnight: "There are no active trains right now.", todayDistributionTitle: "Delay distribution", todayDistributionBody: "The distribution uses observations with usable delay only; coverage and missing evidence remain separate.", comparisonDescription: "Mean for the same weekday and hour over recent historical evidence.", stationContext: "Station", punctualityHelp: "A stop call is considered punctual when its delay is 2 minutes or less compared with the scheduled time.", coverageHelp: "Percentage of scheduled stop calls for which usable evidence is available. Missing evidence is not automatically treated as a cancellation.", meanHelp: "Average delay across all stop calls with usable delay evidence included in this summary.", medianHelp: "Approximate central delay: half of the observations are below this value and half are above it." },
  history: { title: "Historical", trend: "Temporal evolution", distribution: "Delay distribution", rankings: "Where delay accumulates", rankingsUnavailable: "Rankings are not exposed for this context by the current public data contract.", matrix: "Daily matrix", filters: "Filters", from: "From", to: "To", hour: "Hour", allHours: "All", allDirections: "Both directions", apply: "Apply", sample: "sample", insufficient: "Insufficient sample", currentDay: "The selected data is still processing.", finalizationUnknown: "Finalization could not be verified for all selected service days.", days: "Days", allDays: "All", weekdays: "Weekdays", weekend: "Weekend", monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", saturday: "Saturday", sunday: "Sunday", matrixRetention: "Detailed matrix data is outside the 30-day retention window.", matrixNoData: "No detailed matrix data is available for this date.", matrixFailed: "The detailed matrix could not be loaded safely. Try again later.", legend: "Legend", stationColumn: "Station", canceled: "canceled", skipped: "skipped", pending: "pending", early: "early", punctual: "punctual", delayed: "delay", severe: "high delay", stationRanking: "Worst-performing stations", worstHours: "Worst hours", hourWeekday: "Hour × weekday", volumeReliability: "Volume and reliability", volumeReliabilityHelp: "Shows scheduled volume, coverage and reliability together so a tiny sample cannot dominate the ranking.", segmentDelay: "Delay added by segment", segmentDelayHelp: "Mean delay change between consecutive stops with usable evidence at both ends, separated by direction.", secondaryAnalysis: "Additional analysis", p90Help: "Approximate 90th percentile derived from the retained histogram: 90% of observations have this delay or less.", coverageSample: "Coverage / sample", scheduledVolume: "Scheduled volume" },
  charts: { delayDistribution: "Delay distribution", meanDelayTrend: "Mean delay trend", early: "Early", punctual: "≤2m", accessibleData: "Chart data", date: "Date", value: "Value", calls: "Stop calls" },
  errors: { temporaryTitle: "Data temporarily unavailable", temporaryBody: "The application could not load this data safely. No internal database details were exposed.", retry: "Try again", invalidFilters: "One or more filters are invalid. Check the dates and selected options." },
  methodology: { title: "Methodology", intro: "What Atodotren measures, where the evidence comes from, and where its limits are." },
  offline: { status: "Offline.", cached: "Showing the last available offline copy.", cachedAt: "Cached", unavailable: "This data is not available offline." },
};
