import type { Messages } from "./types";

export const en: Messages = {
  nav: { home: "Home", live: "Live", history: "Historical", methodology: "Methodology", menu: "Open menu", close: "Close menu", language: "Language", theme: "Theme", refresh: "Auto-refresh", paused: "Paused", active: "Active", primary: "Primary navigation", light: "Light", dark: "Dark" },
  landing: { eyebrow: "Madrid Cercanías, with memory", title: "Delays should not disappear when the journey ends.", body: "Atodotren accumulates public Cercanías evidence so today’s disruption can be read alongside the patterns that repeat over time.", searchLabel: "Search a line or station", searchPlaceholder: "C1, C-1, Atocha, Chamartín…", liveAction: "View today", historyAction: "View history", emptySearch: "No matching line or station.", summaryLive: "Now", summaryHistory: "Accumulated", liveSummaryDetail: "Status, coverage and trains", historySummaryDetail: "Patterns that remain", footerDescription: "independent public-accountability project", methodology: "How we measure — and what we cannot claim" },
  common: { coverage: "Coverage", freshness: "Freshness", finalized: "Finalized", unfinalized: "Incomplete day", precision: "Precision", updated: "Updated", scheduled: "Scheduled", observed: "With evidence", punctuality: "Punctuality", mean: "Mean", median: "Approx. median", cancellation: "Canceled", missing: "Missing evidence", noData: "No data", details: "Details", direction: "Direction", line: "Line", station: "Station", loading: "Loading", state: "State", confidence: "Confidence", dataMetadata: "Data metadata" },
  live: { title: "Today’s service", networkTitle: "All lines", comparison: "Usual comparison", trains: "Active trains", activeTrains: "active trains", schematic: "Line schematic", inferred: "Feed-derived inferred position; this is not GPS.", reported: "Renfe-reported information", nextArrival: "Scheduled arrival", probableArrival: "Probable arrival", sourceArrival: "Reported arrival", observedPresence: "Observed presence", autoRefresh: "Refreshes every 30s", refreshing: "Refreshing data", hiddenTabPause: "Refresh pauses in hidden tabs", overnight: "There are no active trains right now.", todayDistributionTitle: "How today’s delay is distributed", todayDistributionBody: "The distribution uses observations with usable delay only; coverage and missing evidence remain separate.", comparisonDescription: "Mean for the same weekday/hour when sufficient evidence exists.", stationContext: "Station" },
  history: { title: "Historical", trend: "Temporal evolution", distribution: "Delay distribution", rankings: "Where delay accumulates", matrix: "Daily matrix", filters: "Filters", from: "From", to: "To", hour: "Hour", allHours: "All", allDirections: "Both directions", apply: "Apply", sample: "sample", insufficient: "Insufficient sample", currentDay: "The current service day is not finalized yet.", days: "Days", allDays: "All", weekdays: "Weekdays", weekend: "Weekend", monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", matrixRetention: "Detailed matrix data is only available inside the 30-day retention window.", legend: "Legend", stationColumn: "Station", canceled: "canceled", skipped: "skipped", pending: "pending" },
  charts: { delayDistribution: "Delay distribution", meanDelayTrend: "Mean delay trend", early: "Early" },
  methodology: { title: "Methodology", intro: "What Atodotren measures, where the evidence comes from, and where its limits are." },
  offline: { status: "Offline.", cached: "Showing the last available offline copy.", cachedAt: "Cached", unavailable: "This data is not available offline." },
};
