import type { Messages } from "./types";

export const es: Messages = {
  nav: { home: "Inicio", live: "En directo", history: "Histórico", methodology: "Metodología", menu: "Abrir menú", close: "Cerrar menú", language: "Idioma", theme: "Tema", refresh: "Actualización automática", paused: "Pausada", active: "Activa", primary: "Navegación principal", light: "Claro", dark: "Oscuro" },
  landing: { eyebrow: "Cercanías Madrid, con memoria", title: "Los retrasos no desaparecen al llegar a destino.", body: "Atodotren acumula la evidencia pública de Cercanías para ver qué está ocurriendo ahora y qué patrones se repiten con el tiempo.", searchLabel: "Busca una línea o estación", searchPlaceholder: "C1, C-1, Atocha, Chamartín…", liveAction: "Ver hoy", historyAction: "Ver histórico", emptySearch: "No encontramos coincidencias.", summaryLive: "Ahora", summaryHistory: "Acumulado", liveSummaryDetail: "Estado, cobertura y trenes", historySummaryDetail: "Patrones que permanecen", footerDescription: "proyecto independiente de rendición de cuentas", methodology: "Cómo medimos y qué no podemos afirmar" },
  common: { coverage: "Cobertura", freshness: "Frescura", finalized: "Finalizado", unfinalized: "Día incompleto", precision: "Precisión", updated: "Actualizado", scheduled: "Programados", observed: "Con evidencia", punctuality: "Puntualidad", mean: "Media", median: "Mediana aprox.", cancellation: "Cancelados", missing: "Sin evidencia", noData: "Sin datos", details: "Detalles", direction: "Dirección", line: "Línea", station: "Estación", loading: "Cargando", state: "Estado", confidence: "Confianza", dataMetadata: "Metadatos de los datos" },
  live: { title: "Estado de hoy", networkTitle: "Todas las líneas", comparison: "Comparación habitual", trains: "Trenes activos", activeTrains: "trenes activos", schematic: "Esquema de línea", inferred: "Posición inferida a partir del feed; no es GPS.", reported: "Información reportada por Renfe", nextArrival: "Llegada programada", probableArrival: "Llegada probable", sourceArrival: "Llegada reportada", observedPresence: "Presencia observada", autoRefresh: "Se actualiza cada 30 s", refreshing: "Actualizando datos", hiddenTabPause: "La actualización se suspende en pestañas ocultas", overnight: "No hay trenes activos en este momento.", todayDistributionTitle: "Cómo se reparte el retraso de hoy", todayDistributionBody: "La distribución usa únicamente observaciones con retraso utilizable; cobertura y ausencias se muestran por separado.", comparisonDescription: "Media para el mismo día de semana y franja cuando hay muestra suficiente.", stationContext: "Estación" },
  history: { title: "Histórico", trend: "Evolución temporal", distribution: "Distribución de retrasos", rankings: "Dónde se acumula el retraso", matrix: "Matriz del día", filters: "Filtros", from: "Desde", to: "Hasta", hour: "Hora", allHours: "Todas", allDirections: "Ambas direcciones", apply: "Aplicar", sample: "muestra", insufficient: "Muestra insuficiente", currentDay: "El día actual todavía no está finalizado.", days: "Días", allDays: "Todos", weekdays: "Laborables", weekend: "Fin de semana", monday: "Lunes", tuesday: "Martes", wednesday: "Miércoles", thursday: "Jueves", friday: "Viernes", matrixRetention: "La matriz detallada solo está disponible durante la ventana de retención de 30 días.", legend: "Leyenda", stationColumn: "Estación", canceled: "cancelado", skipped: "omitido", pending: "pendiente" },
  charts: { delayDistribution: "Distribución de retrasos", meanDelayTrend: "Evolución temporal del retraso medio", early: "Temprano" },
  methodology: { title: "Metodología", intro: "Qué mide Atodotren, de dónde sale la evidencia y dónde están sus límites." },
  offline: { status: "Sin conexión.", cached: "Mostrando la última copia disponible sin conexión.", cachedAt: "Guardada", unavailable: "Este dato no está disponible sin conexión." },
};
