import type { Lang } from "@/lib/domain/contracts";

interface MethodSection { readonly title: string; readonly paragraphs: readonly string[] }
interface MethodCopy { readonly kicker: string; readonly title: string; readonly intro: string; readonly sections: readonly MethodSection[] }

export const methodologyCopy: Readonly<Record<Lang, MethodCopy>> = {
  es: {
    kicker: "Evidencia antes que precisión falsa",
    title: "Cómo medimos Cercanías",
    intro: "Andén Infinito transforma datos públicos de Renfe en una historia acumulada del servicio. Separa lo reportado, lo calculado y lo que sencillamente no puede saberse con la evidencia disponible.",
    sections: [
      { title: "Fuentes", paragraphs: ["Usamos el GTFS estático de Renfe para horarios, recorridos y estaciones, y GTFS-Realtime para actualizaciones de viaje, posiciones de vehículo y alertas. El navegador nunca consulta estas fuentes ni la base de datos directamente: el servidor publica modelos de lectura acotados.", "La salud del feed y la frescura de un tren son conceptos distintos. Un sondeo reciente puede indicar que la fuente está operativa, pero una fila de vehículo antigua no vuelve a ser activa por ello: las vistas en directo solo usan estados frescos del día de servicio actual de Madrid."] },
      { title: "Retraso reportado y calculado", paragraphs: ["Renfe puede informar una hora estimada de llegada y/o un retraso en segundos. Cuando existe una hora de llegada correctamente enlazada con el horario, calculamos su desviación y conservamos también el retraso proporcionado por Renfe. Las discrepancias no se borran.", "Consideramos puntual una llegada con retraso de 120 segundos o menos. El sistema conserva segundos enteros y redondea solo para mostrar resultados."] },
      { title: "Retraso acumulado por trayectos", paragraphs: ["La métrica acumulada de portada es por trayecto, no por parada ni por pasajero. Cada trayecto aporta su último retraso utilizable no negativo. Mientras sigue en marcha, una evidencia posterior sustituye a la anterior; al llegar a su última parada, la contribución final queda congelada.", "Si el mismo tren físico inicia otro trayecto, ese nuevo trayecto cuenta por separado. El retraso de trayectos activos usa únicamente trayectos con estado de vehículo fresco; el retraso acumulado de hoy suma las contribuciones finales de trayectos terminados y la contribución más reciente de los que siguen activos. No son minutos-pasajero ni la suma del retraso en cada parada."] },
      { title: "Predicciones, presencia y posición", paragraphs: ["Un retraso propagado desde una parada anterior sirve únicamente como predicción en directo: nunca se convierte en evidencia histórica de una parada posterior. STOPPED_AT se interpreta como presencia observada en la parada en ese instante, no como una hora de llegada exacta.", "El mapa en directo es esquemático. Cuando situamos un tren entre estaciones a partir del estado del feed, lo etiquetamos como posición inferida. No representa coordenadas GPS ni precisión geográfica."] },
      { title: "Cancelaciones y huecos", paragraphs: ["Las paradas canceladas, omitidas y sin evidencia se mantienen como estados distintos y se excluyen de la distribución de retrasos. La desaparición de un viaje no se interpreta automáticamente como cancelación. La cobertura indica qué parte de las oportunidades programadas dispone de evidencia utilizable."] },
      { title: "Percentiles y agregados", paragraphs: ["La mediana y el P90 históricos se aproximan a partir del histograma de retrasos retenido. El P90 es el valor por debajo o igual al cual queda aproximadamente el 90% de la evidencia utilizable. Los agregados de tramo miden el cambio de retraso entre paradas consecutivas cuando existe evidencia utilizable en ambos extremos."] },
      { title: "Días incompletos y cierre", paragraphs: ["El día de servicio no termina necesariamente a medianoche. Los datos del día actual pueden estar incompletos y se identifican como no finalizados. Tras el cierre y las comprobaciones de consistencia, los agregados quedan sellados para esa versión del algoritmo."] },
      { title: "Agregación y retención", paragraphs: ["El detalle reconstruible de cada viaje y la matriz exacta se conserva durante 30 días de servicio completados. Después permanecen agregados diarios por hora y agregados mensuales por horario programado, diseñados para combinarse sin fingir que existe detalle que ya no se conserva."] },
      { title: "Propósito", paragraphs: ["Andén Infinito es una herramienta independiente de rendición de cuentas pública. Su objetivo no es explicar por qué ocurrió cada retraso, sino conservar una evidencia comprensible de cuánto, dónde y con qué cobertura se produjo."] },
    ],
  },
  en: {
    kicker: "Evidence before false precision",
    title: "How we measure Cercanías",
    intro: "Andén Infinito turns Renfe public data into an accumulated record of service performance. It keeps reported, calculated and unknowable facts distinct instead of smoothing those differences away.",
    sections: [
      { title: "Sources", paragraphs: ["We use Renfe static GTFS for timetables, routes and stations, and GTFS-Realtime for trip updates, vehicle positions and alerts. The browser never queries those feeds or PostgreSQL directly: the server exposes bounded read models.", "Feed health and train freshness are separate concepts. A recent successful poll can show that the source is healthy, but it does not make an old vehicle row active: live views only use fresh vehicle states for the current Madrid service date."] },
      { title: "Reported and calculated delay", paragraphs: ["Renfe may provide an estimated arrival timestamp and/or delay in seconds. When an arrival timestamp can be reliably matched to schedule, we calculate its deviation while preserving Renfe’s provided delay separately. Discrepancies are retained rather than silently reconciled.", "A call is punctual at 120 seconds of delay or less. The system stores integer seconds and rounds only for presentation."] },
      { title: "Accumulated journey delay", paragraphs: ["The landing accumulated-delay metric is journey-based, not stop-based or passenger-based. Each journey contributes its latest usable non-negative delay. While it is running, later evidence replaces the earlier contribution; at the final stop, that journey’s contribution freezes.", "If the same physical train starts another journey, that is a separate contribution. Active-journey delay uses only journeys with a fresh vehicle state; today’s accumulated journey delay combines frozen final contributions from completed journeys with the latest contribution from active journeys. It is neither passenger-minutes nor the sum of delay at every stop."] },
      { title: "Predictions, presence and position", paragraphs: ["Delay propagated from an upstream stop is a live prediction only; it never becomes historical evidence for a later stop. STOPPED_AT is treated as observed presence at a stop at that instant, not an exact arrival timestamp.", "The live map is schematic. When a train is placed between stations from feed state, it is explicitly labelled inferred. It is neither GPS nor a claim of geographic precision."] },
      { title: "Cancellations and gaps", paragraphs: ["Canceled, skipped and missing-evidence calls remain separate states and are excluded from delay distributions. A journey disappearing from the feed is not automatically a cancellation. Coverage tells you how much of the scheduled denominator has usable evidence."] },
      { title: "Percentiles and aggregates", paragraphs: ["Historical median and P90 are approximated from the retained delay histogram. P90 is the value at or below which roughly 90% of usable evidence falls. Segment aggregates measure the change in delay between consecutive stops when usable evidence exists at both ends."] },
      { title: "Incomplete days and finalization", paragraphs: ["A service day does not necessarily end at civil midnight. Current-day values can be incomplete and are marked unfinalized. After the service day closes and consistency checks pass, aggregates are sealed for that algorithm version."] },
      { title: "Aggregation and retention", paragraphs: ["Reconstructable journey detail and exact timetable matrices are retained for 30 completed service days. After that, daily hourly aggregates and monthly scheduled-slot aggregates remain, designed to combine correctly without pretending old train-level detail still exists."] },
      { title: "Purpose", paragraphs: ["Andén Infinito is an independent public-accountability tool. It does not claim to explain the cause of each delay; it preserves understandable evidence of how much delay occurred, where it accumulated and how complete the underlying evidence was."] },
    ],
  },
};
