export interface Messages {
  nav: { home: string; live: string; history: string; methodology: string; menu: string; close: string; language: string; theme: string; refresh: string; paused: string; active: string; primary: string; light: string; dark: string };
  landing: { eyebrow: string; title: string; body: string; searchLabel: string; searchPlaceholder: string; liveAction: string; historyAction: string; emptySearch: string; summaryLive: string; summaryHistory: string; liveSummaryDetail: string; historySummaryDetail: string; footerDescription: string; methodology: string };
  common: { coverage: string; freshness: string; finalized: string; unfinalized: string; precision: string; updated: string; scheduled: string; observed: string; punctuality: string; mean: string; median: string; cancellation: string; missing: string; noData: string; details: string; direction: string; line: string; station: string; loading: string; state: string; confidence: string; dataMetadata: string };
  live: { title: string; networkTitle: string; comparison: string; trains: string; activeTrains: string; schematic: string; inferred: string; reported: string; nextArrival: string; probableArrival: string; sourceArrival: string; observedPresence: string; autoRefresh: string; refreshing: string; hiddenTabPause: string; overnight: string; todayDistributionTitle: string; todayDistributionBody: string; comparisonDescription: string; stationContext: string };
  history: { title: string; trend: string; distribution: string; rankings: string; matrix: string; filters: string; from: string; to: string; hour: string; allHours: string; allDirections: string; apply: string; sample: string; insufficient: string; currentDay: string; days: string; allDays: string; weekdays: string; weekend: string; monday: string; tuesday: string; wednesday: string; thursday: string; friday: string; matrixRetention: string; legend: string; stationColumn: string; canceled: string; skipped: string; pending: string };
  charts: { delayDistribution: string; meanDelayTrend: string; early: string };
  methodology: { title: string; intro: string };
  offline: { status: string; cached: string; cachedAt: string; unavailable: string };
}
